# Usa una imagen base ligera de Python 3.11
FROM python:3.11-slim

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia los archivos necesarios
COPY requirements.txt requirements.txt
# Instala las dependencias
RUN pip install -r requirements.txt

# Copia el código de la aplicación
COPY . .

# Exponer el puerto en el que corre la app
EXPOSE 5000
ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0
# Agregar variable de entorno con con  la database 
ENV FLASK_DEBUG  "0"



# Comando para correr la app
CMD ["flask", "run"]