name: Deploy to Elastic Beanstalk
on:
    pull_request:
      branches:
        - dev
    workflow_dispatch:        
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code 
          uses: actions/checkout@v4.1.7
          with:
              ref: dev
        
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1
        
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3.5.0   
        - name: Log in to Amazon ECR  
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v2
