name: Deploy Api-business In Elastic Beanstalk
on:
    pull_request:
      branches:
        - dev
    workflow_dispatch:        
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code 
          uses: actions/checkout@v4.1.7
          with:
              ref: dev
        
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1

        - name: Log in to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v1    
          
        - name: Build and push Docker image to ECR
          env:
            ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            ECR_REPOSITORY: autoperfecto-business-api
            IMAGE_TAG: ${{ github.sha }}
          run: |
            docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./backend/api-business
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG


        - name: Create Dockerrun.aws.json with environment variables
          run: |
            echo '{
              "AWSEBDockerrunVersion": "1",
              "Image": {
                "Name": "${{ steps.login-ecr.outputs.registry }}/autoperfecto-business-api:${{ github.sha }}",
                "Update": "true"
              },
              "Ports": [
                {
                  "ContainerPort": "5000"
                }
              ]
            }' > ./backend/api-business/Dockerrun.aws.json 
        - run: |
            cd backend/api-business
            zip -r ../../app-build.zip . 
        
        - name: Update Elastic Beanstalk environment to use the new Docker image
          uses: einaregilsson/beanstalk-deploy@v21
          with: 
            aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            region: us-east-1
            application_name : auto-perfecto-business-api
            environment_name: auto-perfecto-business-api-qa 
            deployment_package: app-build.zip
            version_label:  ${{ github.sha }}
