name: Deploy Api-Auth In Elastic Beanstalk
on:
    pull_request:
      branches:
        - dev
    workflow_dispatch:        
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code 
          uses: actions/checkout@v4.1.7
          with:
              ref: dev
        
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1

                 
        - run: |
            cd backend/api-auth
            zip -r ../../app-build.zip . 
        
        - name: Update Elastic Beanstalk environment to use the new Docker image
          uses: einaregilsson/beanstalk-deploy@v21
          with: 
            aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            region: us-east-1
            application_name : auto-perfecto-auth-api
            environment_name: auto-perfecto-auth-api-qa 
            deployment_package: app-build.zip
            version_label:  ${{ github.sha }}
